# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94b9a37efdb67393e920985848690af9a1a0eda29b0c113dee72d69a6cabc7f503b1d83b24fba650505c20266440fb0f89e5376f1b0f1710646ed5e6b3ebdccf

test:
  secret_key_base: 5cd35e76d8fb44a805d175acd156cb9e0fda6b9c345070653deec5bbeed288b09cab5044dd20af8a9f71244abdcba214e04fb305d6d32bba68e26dff0a64dd5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
